
# $HOME_HOST/$OSTYPE を.zshrcで設定しておく
# current directory のgitリポジトリ情報を取得
_set_env_git_current_branch() {
    GIT_CURRENT_REPOSITORY=`git config --local -l 2>/dev/null | awk -F/ '/^remote.origin.url/{print $NF}'`
    GIT_CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD 2>/dev/null`
    if [ "$GIT_CURRENT_REPOSITORY" = "" ] || [ "$GIT_CURRENT_BRANCH" = "" ]
    then
        GIT_CURRENT_REPOSITORY="repos"
        GIT_CURRENT_BRANCH="none"
    fi
}

_update_rprompt () {
    RPROMPT="[$GIT_CURRENT_REPOSITORY:$GIT_CURRENT_BRANCH]"
}

precmd()
{
    _set_env_git_current_branch
    _update_rprompt
}

chpwd()
{
    _set_env_git_current_branch
    _update_rprompt
}

if [ $UID -eq 0 ]
then
    U_COLOR="01;37;41" # root: bload,white/red
else
    U_COLOR="01;37;44" # other: bload,white/blue
fi

if [ $HOST = $HOME_HOST ]
then
    H_COLOR="00" # homehost: default
else
    H_COLOR="00;30;43" # other: black/yellow
fi

PROMPT=$'[%{\e['${U_COLOR}$'m%}%n%{\e[0m%}@%{\e['${H_COLOR}$'m%}%m%{\e[0m%}:%c]%# '

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

export CLICOLOR=1
export PATH="$PATH:$HOME/bin"

setopt extended_history

LISTMAX=0

autoload -Uz compinit; compinit

zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin

setopt append_history

setopt auto_list

setopt list_packed

setopt auto_menu

setopt auto_param_keys

setopt no_beep

setopt hist_ignore_dups

setopt hist_no_store

export GIT_PAGER="lv -c"

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "/Users/yashiro/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/yashiro/.sdkman/bin/sdkman-init.sh"

# anyenv $ git clone https://github.com/riywo/anyenv ~/.anyenv
export PATH="$HOME/.anyenv/bin:$PATH"
eval "$(anyenv init -)"

source ~/dotfiles/zsh/alias.sh
